name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:        
      - 'v*' 

jobs:
  build:
    uses: xoxfaby/actions/.github/workflows/dotnet-publish.yml@main

  release-github:
    needs: release-thunderstore
    uses: xoxfaby/actions/.github/workflows/release.yml@main
